spring:
  application:
    name: flota-service

server:
  port: 8083

vehiculo:
  service:
    url: http://localhost:8081

cotizacion:
  service:
    url: http://localhost:8082


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
